### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by hackdefendr** [UltimateHackers/Decodify#13]
I ran the most simple of tests and it failed to crack it.

```
$ echo "marvel is better than dc" | md5sum
4003a149f18c3210b413169b99187096  -

$ dcode 4003a149f18c3210b413169b99187096

    __                         __
  |/  |                   | / /
  |   | ___  ___  ___  ___|  (
  |   )|___)|    |   )|   )| |___ \   )
  |__/ |__  |__  |__/ |__/ | |     \_/
                                    /
[-] Its a MD5 Hash but I failed to crack it.
```

Did I miss something?

**Comment by 3lixy** [comment]
I would assume that www.nitrxgen.net does not have it.

Trying http://www.nitrxgen.net/md5db/4003a149f18c3210b413169b99187096 returns an empty response.

See https://github.com/UltimateHackers/Decodify/blob/master/dcode#L97 for where it is in the decodify code.

I would assume not every computation was done at that length of string as the storage costs would get pretty insane.
